//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Feb 24 2013 03:04:31).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#pragma mark -

//
// File: /System/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl
// UUID: A110E0D5-DF7C-37C0-9AD6-81A3CCEB12C5
//
//                           Arch: x86_64
//                Current version: 8.5.9
//          Compatibility version: 8.5.0
//       Minimum Mac OS X version: 10.7.0
//                    SDK version: 0.0.0
//

//
// This file does not contain any Objective-C runtime information.
//
